@baseUrl = http://localhost:3001
@apiUrl = {{baseUrl}}/api
@json = application/json

POST {{apiUrl}}/auth/register
Content-Type: {{json}}

{
 "email": "hello@mail.com",
 "password": "1234"
}

###

POST {{apiUrl}}/auth/sign-in
Content-Type: {{json}}

{
 "email": "hello@mail.com",
 "password": "1234"
}
